version: '4'

services:
  web:
    build: .
    ports:
      - "5253-5254:5253"
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app.py
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
    networks:
      - app-network
  redis:
    image: "redis:alpine"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
